org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=/home/sebastian/Descargas/android-studio/jbr
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.configuration-cache=true
